#version 460
#extension GL_EXT_ray_tracing : require

struct HitPayload
{
    vec3 hitColor;
};

layout(location = 0) rayPayloadEXT HitPayload hitPayload;

layout(binding = 0, set = 0) uniform accelerationStructureEXT topLevelAS;
layout(binding = 0, set = 1, rgba32f) uniform image2D image;
layout(binding = 0, set = 2) uniform MATRIXS
{
    mat4 view;
    mat4 Project;
};

void main()
{
    imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(0.5, 0.5, 0.5, 1.0));
}
